---
- name: "Check SolidFire Compliance"
  delegate_to: localhost

  block:
    - name: Ensure the system has the required python libraries
      pip:
        name: [ 'ansible>=2.10', 'jmespath==0.10.0', 'pyyaml>=5.3.1' ]
        state: present

    - na_compliance:
        rule_file: "{{ role_path }}/files/sf_compliance_rules.yaml"
        cpu_file: "{{ role_path }}/files/sf_supported_cpus.yaml"
        facts: "{{ ansible_facts }}"
        report_path: "{{ sf_compliance_report_path }}"
      register: sf_compliance_result

    - fail:
        msg: "{{ inventory_hostname }} is not compliant"
      when: not sf_compliance_result.compliant

    - debug:
        msg: "{{ inventory_hostname }} is compliant"
      when: sf_compliance_result.compliant

  always:
    - debug:
        msg: "{{ sf_compliance_result.report }}"
      when: sf_print_report
